[package]
name = "multi-repo-sync"
version = "1.1.4"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
octocrab = "0.41.2"
serde = "1.0.215"
serde_json = "1.0.132"
regex = "1.11.1"
